
import java.sql.Connection;
import static java.sql.DriverManager.println;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bayadzka
 */
public class SHUBulanan extends javax.swing.JFrame {

    /**
     * Creates new form SHUBulanan
     */
    Connection koneksi;
    hitungSHU ESHAU = new hitungSHU();
    public SHUBulanan() {
        initComponents();
        koneksi = DatabaseConnection.getKoneksi("localhost","3306","root","","koperasi_guru");
        showData();
    }
    
    DefaultTableModel dtm;
    public void showData(){
        String[] kolom = {"No","Nama","Pokok","Wajib","Sukarela","Total","Prosentase Simpanan","Uang","Barang","Prosentase Pinjaman","SHU Simpanan","SHU Pinjaman","SHU TOTAL"};
        dtm = new DefaultTableModel(null, kolom);
        try {
            Statement stmt = koneksi.createStatement();
            String query = "SELECT anggota.nama, penyimpanan.simp_pokok, penyimpanan.simp_wajib, penyimpanan.simp_sukarela, "
                    + "peminjaman.jenis_peminjaman, peminjaman.jumlah_pinjam, shu.shu_simpanan, shu.shu_pinjaman, shu.shu_total, "
                    + "SUM(simp_pokok)+SUM(simp_wajib)+SUM(simp_sukarela) as 'totalsimp', "
                    + "SUM(jumlah_pinjam) as totalpinj "
                    + "FROM anggota, penyimpanan, peminjaman, shu "
                    + "WHERE anggota.id_anggota = penyimpanan.id_anggota AND anggota.id_anggota = peminjaman.id_anggota "
                    + "AND anggota.id_anggota = shu.id_anggota AND penyimpanan.id_penyimpanan = shu.id_penyimpanan AND "
                    + "peminjaman.kd_peminjaman = shu.kd_peminjaman";
            ResultSet rs = stmt.executeQuery(query);
            int no =1;
            while(rs.next()){
                String nama = rs.getString("nama");
                int pokok = rs.getInt("simp_pokok");
                int wajib = rs.getInt("simp_wajib");
                int sukarela = rs.getInt("simp_sukarela");
                int total_simpanan = pokok + wajib +sukarela;
                int uang = ESHAU.getuang(rs.getString("jenis_peminjaman"),rs.getInt("jumlah_pinjam"));
                int barang = ESHAU.getbarang(rs.getString("jenis_peminjaman"),rs.getInt("jumlah_pinjam"));
                int total_pinjaman = uang+barang;
                int shu_simpanan = ESHAU.getshusimpanan(total_simpanan, rs.getInt("totalsimp"));
                int shu_pinjaman = ESHAU.getshupinjaman(total_pinjaman, rs.getInt("totalpinj"));
                int total_shu = shu_simpanan + shu_pinjaman;
                int prosentase_pinjaman = ESHAU.getprosentasepinjaman(shu_pinjaman);
                int prosentase_simpanan = ESHAU.getprosentasesimpanan(shu_simpanan);
                System.out.println("simpanan"+shu_simpanan);
                
                dtm.addRow(new String[]{no+"",nama,Integer.toString(pokok),Integer.toString(wajib),Integer.toString(sukarela),Integer.toString(total_simpanan),Integer.toString(prosentase_simpanan),
                    Integer.toString(uang),Integer.toString(barang),Integer.toString(total_pinjaman),Integer.toString(prosentase_pinjaman),
                    Integer.toString(shu_simpanan),Integer.toString(shu_pinjaman),Integer.toString(total_shu)});
                no++;
                
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        tbl_shu.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_shu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DAFTAR PERINCIAN SHU ANGGOTA KOPERASI");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Untuk Jasa Simpanan");

        jLabel3.setText("Untuk Jasa Pinjaman");

        jLabel4.setText("Jumlah");

        jLabel5.setText(":");

        jLabel6.setText(":");

        jLabel7.setText(":");

        tbl_shu.setBackground(new java.awt.Color(153, 255, 51));
        tbl_shu.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        tbl_shu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_shu.setFillsViewportHeight(true);
        tbl_shu.setGridColor(new java.awt.Color(0, 102, 51));
        tbl_shu.setRowSelectionAllowed(false);
        tbl_shu.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tbl_shu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_shuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_shu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_shuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_shuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_shuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SHUBulanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SHUBulanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SHUBulanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SHUBulanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SHUBulanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_shu;
    // End of variables declaration//GEN-END:variables
}
