
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bayadzka
 */
public class SHUTahunan extends javax.swing.JFrame {

    /**
     * Creates new form SHUTahunan
     */
    Connection koneksi;
    public SHUTahunan() {
        initComponents();
        koneksi = DatabaseConnection.getKoneksi("localhost","3306","root","","koperasi_guru");
        showData();
    }
    
    DefaultTableModel dtm;
    public void showData(){
        String[] kolom = {"No","Nama","Pokok","Wajib","Sukarela","Total","Prosentase Simpanan"};
        dtm = new DefaultTableModel(null, kolom);
        try {
            Statement stmt = koneksi.createStatement();
            String query = "SELECT anggota.nama as'nama', sum(det_simpanan.pokok)as'pokok', sum(det_simpanan.wajib) as'wajib',"
                    + "sum(det_simpanan.sukarela)as'sukarela' pinjaman.uang as'uang', pinjaman.barang as'barang'"
                    + "from shu, anggota, simpanan, det_simpanan, pinjaman, det_pinjaman "
                    + "where anggota.id_anggota=shu.id_anggota and anggota.id_anggota=pinjaman.id_anggota and "
                    + "anggota.id_anggota=simpanan.id_anggota and simpanan.id_simpanan=det_simpanan and simpanan.id_simpanan=det_simpanan.id_simpanan "
                    + "simpanan.id_simpanan=shu.id_simpanan and pinjaman.id_pinjaman=det_pijaman.id_pinjaman and pinjaman.id_pinjaman=shu.id_pinjaman "
                    + "group by anggota.nama";
            ResultSet rs = stmt.executeQuery(query);
            int no =1;
            String shusimp = "select sum(det_simpanan.pokok)+sum(det_simpanan.wajib)+sum(det_simpanan.sukarela) as 'shusimp' from det_simpanan";
            ResultSet rs1 = stmt.executeQuery(shusimp);
            int shusimpa = rs1.getInt(shusimp);
            String shupinj = "select sum(pinjaman.uang)+sum(pinjaman.barang) as 'shupinj' from pinjaman";
            ResultSet rs2 = stmt.executeQuery(shupinj);
            int shupinja= rs2.getInt(shupinj);
            while(rs.next()){
                String nama = rs.getString("nama");
                String pokok = rs.getString("pokok");
                String wajib = rs.getString("wajib");
                String sukarela = rs.getString("sukarela");
                int tosim = rs.getInt(pokok+wajib+sukarela);
                String tosimp = Integer.toString(tosim);
                String prosensim = "0";
                String uang = rs.getString("uang");
                String barang = rs.getString("barang");
                int topin = rs.getInt(uang+barang);
                String topinj = Integer.toString(topin);
                String prosenpin = "0";
                int shusim = tosim/shusimpa*32546696;
                String shusimpan = Integer.toString(shusim);
                int shupin = topin/shupinja*48820044;
                String shupinjam = Integer.toString(shupin);
                int toshu = shusim+shupin;
                String totshu = Integer.toString(toshu);
                
                dtm.addRow(new String[]{no+"",nama,pokok,wajib,sukarela,tosimp,prosensim,uang,barang,topinj,prosenpin,shusimpan,shupinjam,totshu});
                no++;
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        tbl_pinjaman.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_simpanan = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_pinjaman = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DAFTAR PERINCIAN SHU ANGGOTA KOPERASI");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("SIMPANAN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("PINJAMAN");

        tbl_simpanan.setBackground(new java.awt.Color(153, 255, 51));
        tbl_simpanan.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        tbl_simpanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_simpanan.setFillsViewportHeight(true);
        tbl_simpanan.setGridColor(new java.awt.Color(0, 102, 51));
        tbl_simpanan.setRowSelectionAllowed(false);
        tbl_simpanan.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tbl_simpanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_simpananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_simpanan);

        tbl_pinjaman.setBackground(new java.awt.Color(153, 255, 51));
        tbl_pinjaman.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        tbl_pinjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_pinjaman.setFillsViewportHeight(true);
        tbl_pinjaman.setGridColor(new java.awt.Color(0, 102, 51));
        tbl_pinjaman.setRowSelectionAllowed(false);
        tbl_pinjaman.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tbl_pinjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pinjamanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_pinjaman);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(296, 296, 296))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_simpananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_simpananMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_simpananMouseClicked

    private void tbl_pinjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pinjamanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_pinjamanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SHUTahunan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SHUTahunan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SHUTahunan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SHUTahunan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SHUTahunan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_pinjaman;
    private javax.swing.JTable tbl_simpanan;
    // End of variables declaration//GEN-END:variables
}
